default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  host: <%= ENV["DB_HOST"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV["DB_PORT"] %>

development:
  <<: *default
  database: BillsTracker_development

test:
  <<: *default
  database: BillsTracker_test

production:
  <<: *default
  database: BillsTracker_production
  username: BillsTracker
  password: <%= ENV["BILLSTRACKER_DATABASE_PASSWORD"] %>
